// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.29.1
// 	protoc        v3.21.10
// source: prodvana/protection/protection_config.proto

package protection

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	common_config "github.com/prodvana/prodvana-public/go/prodvana-sdk/proto/prodvana/common_config"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProtectionConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Types that are assignable to ExecConfig:
	//
	//	*ProtectionConfig_TaskConfig
	ExecConfig isProtectionConfig_ExecConfig `protobuf_oneof:"exec_config"`
}

func (x *ProtectionConfig) Reset() {
	*x = ProtectionConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_prodvana_protection_protection_config_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProtectionConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtectionConfig) ProtoMessage() {}

func (x *ProtectionConfig) ProtoReflect() protoreflect.Message {
	mi := &file_prodvana_protection_protection_config_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtectionConfig.ProtoReflect.Descriptor instead.
func (*ProtectionConfig) Descriptor() ([]byte, []int) {
	return file_prodvana_protection_protection_config_proto_rawDescGZIP(), []int{0}
}

func (x *ProtectionConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (m *ProtectionConfig) GetExecConfig() isProtectionConfig_ExecConfig {
	if m != nil {
		return m.ExecConfig
	}
	return nil
}

func (x *ProtectionConfig) GetTaskConfig() *common_config.TaskConfig {
	if x, ok := x.GetExecConfig().(*ProtectionConfig_TaskConfig); ok {
		return x.TaskConfig
	}
	return nil
}

type isProtectionConfig_ExecConfig interface {
	isProtectionConfig_ExecConfig()
}

type ProtectionConfig_TaskConfig struct {
	// Inline task config with retry, template support.
	TaskConfig *common_config.TaskConfig `protobuf:"bytes,2,opt,name=task_config,json=taskConfig,proto3,oneof"`
}

func (*ProtectionConfig_TaskConfig) isProtectionConfig_ExecConfig() {}

type ProtectionInstanceConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Config *ProtectionConfig `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
}

func (x *ProtectionInstanceConfig) Reset() {
	*x = ProtectionInstanceConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_prodvana_protection_protection_config_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProtectionInstanceConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtectionInstanceConfig) ProtoMessage() {}

func (x *ProtectionInstanceConfig) ProtoReflect() protoreflect.Message {
	mi := &file_prodvana_protection_protection_config_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtectionInstanceConfig.ProtoReflect.Descriptor instead.
func (*ProtectionInstanceConfig) Descriptor() ([]byte, []int) {
	return file_prodvana_protection_protection_config_proto_rawDescGZIP(), []int{1}
}

func (x *ProtectionInstanceConfig) GetConfig() *ProtectionConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

var File_prodvana_protection_protection_config_proto protoreflect.FileDescriptor

var file_prodvana_protection_protection_config_proto_rawDesc = []byte{
	0x0a, 0x2b, 0x70, 0x72, 0x6f, 0x64, 0x76, 0x61, 0x6e, 0x61, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x13, 0x70,
	0x72, 0x6f, 0x64, 0x76, 0x61, 0x6e, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x1a, 0x17, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c,
	0x69, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x21, 0x70, 0x72, 0x6f,
	0x64, 0x76, 0x61, 0x6e, 0x61, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x5f, 0x63, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x2f, 0x74, 0x61, 0x73, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xae,
	0x01, 0x0a, 0x10, 0x50, 0x72, 0x6f, 0x74, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x12, 0x3f, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x42, 0x2b, 0xfa, 0x42, 0x28, 0x72, 0x26, 0x10, 0x01, 0x18, 0x3f, 0x32, 0x20, 0x5e, 0x5b,
	0x61, 0x2d, 0x7a, 0x5d, 0x28, 0x5b, 0x61, 0x2d, 0x7a, 0x30, 0x2d, 0x39, 0x2d, 0x5d, 0x2a, 0x5b,
	0x61, 0x2d, 0x7a, 0x30, 0x2d, 0x39, 0x5d, 0x29, 0x7b, 0x30, 0x2c, 0x31, 0x7d, 0x24, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x45, 0x0a, 0x0b, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x63, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x70, 0x72, 0x6f, 0x64,
	0x76, 0x61, 0x6e, 0x61, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x5f, 0x63, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x48, 0x00, 0x52,
	0x0a, 0x74, 0x61, 0x73, 0x6b, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x42, 0x12, 0x0a, 0x0b, 0x65,
	0x78, 0x65, 0x63, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x03, 0xf8, 0x42, 0x01, 0x22,
	0x59, 0x0a, 0x18, 0x50, 0x72, 0x6f, 0x74, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x73,
	0x74, 0x61, 0x6e, 0x63, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x3d, 0x0a, 0x06, 0x63,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x70, 0x72,
	0x6f, 0x64, 0x76, 0x61, 0x6e, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x65, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x52, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x42, 0x4f, 0x5a, 0x4d, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x72, 0x6f, 0x64, 0x76, 0x61, 0x6e,
	0x61, 0x2f, 0x70, 0x72, 0x6f, 0x64, 0x76, 0x61, 0x6e, 0x61, 0x2d, 0x70, 0x75, 0x62, 0x6c, 0x69,
	0x63, 0x2f, 0x67, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x64, 0x76, 0x61, 0x6e, 0x61, 0x2d, 0x73, 0x64,
	0x6b, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x64, 0x76, 0x61, 0x6e, 0x61,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_prodvana_protection_protection_config_proto_rawDescOnce sync.Once
	file_prodvana_protection_protection_config_proto_rawDescData = file_prodvana_protection_protection_config_proto_rawDesc
)

func file_prodvana_protection_protection_config_proto_rawDescGZIP() []byte {
	file_prodvana_protection_protection_config_proto_rawDescOnce.Do(func() {
		file_prodvana_protection_protection_config_proto_rawDescData = protoimpl.X.CompressGZIP(file_prodvana_protection_protection_config_proto_rawDescData)
	})
	return file_prodvana_protection_protection_config_proto_rawDescData
}

var file_prodvana_protection_protection_config_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_prodvana_protection_protection_config_proto_goTypes = []interface{}{
	(*ProtectionConfig)(nil),         // 0: prodvana.protection.ProtectionConfig
	(*ProtectionInstanceConfig)(nil), // 1: prodvana.protection.ProtectionInstanceConfig
	(*common_config.TaskConfig)(nil), // 2: prodvana.common_config.TaskConfig
}
var file_prodvana_protection_protection_config_proto_depIdxs = []int32{
	2, // 0: prodvana.protection.ProtectionConfig.task_config:type_name -> prodvana.common_config.TaskConfig
	0, // 1: prodvana.protection.ProtectionInstanceConfig.config:type_name -> prodvana.protection.ProtectionConfig
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_prodvana_protection_protection_config_proto_init() }
func file_prodvana_protection_protection_config_proto_init() {
	if File_prodvana_protection_protection_config_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_prodvana_protection_protection_config_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProtectionConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_prodvana_protection_protection_config_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProtectionInstanceConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_prodvana_protection_protection_config_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*ProtectionConfig_TaskConfig)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_prodvana_protection_protection_config_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_prodvana_protection_protection_config_proto_goTypes,
		DependencyIndexes: file_prodvana_protection_protection_config_proto_depIdxs,
		MessageInfos:      file_prodvana_protection_protection_config_proto_msgTypes,
	}.Build()
	File_prodvana_protection_protection_config_proto = out.File
	file_prodvana_protection_protection_config_proto_rawDesc = nil
	file_prodvana_protection_protection_config_proto_goTypes = nil
	file_prodvana_protection_protection_config_proto_depIdxs = nil
}
