package types

type ApplicationId string
type ReleaseChannelId string
type RuntimeId string
type UserId string
type ApiTokenId string
type OrganizationId string
type ServiceId string
type PipelineId string
type IntegrationId string
type ManagedResourceId string
type SecretId string
type InsightId string
type RegistryCacheId string
type DesiredStateId string
type EventId string
type SignalId string
type RepositoryId string
type NotificationId string
type ProtectionId string
type ProtectionAttachmentId string
type DeliveryExtensionId string
type DeliveryExtensionInstanceId string
type DeploymentId string
type ReleaseId string
type ConcurrencyLimitId string
type ConcurrencyLeaseId string
type JobId string
