// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: prodvana/common_config/external_link.proto

package common_config

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on ExternalLink with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ExternalLink) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ExternalLink with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ExternalLinkMultiError, or
// nil if none found.
func (m *ExternalLink) ValidateAll() error {
	return m.validate(true)
}

func (m *ExternalLink) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Type

	if utf8.RuneCountInString(m.GetUrl()) < 1 {
		err := ExternalLinkValidationError{
			field:  "Url",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetName()) < 1 {
		err := ExternalLinkValidationError{
			field:  "Name",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return ExternalLinkMultiError(errors)
	}

	return nil
}

// ExternalLinkMultiError is an error wrapping multiple validation errors
// returned by ExternalLink.ValidateAll() if the designated constraints aren't met.
type ExternalLinkMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ExternalLinkMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ExternalLinkMultiError) AllErrors() []error { return m }

// ExternalLinkValidationError is the validation error returned by
// ExternalLink.Validate if the designated constraints aren't met.
type ExternalLinkValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ExternalLinkValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ExternalLinkValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ExternalLinkValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ExternalLinkValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ExternalLinkValidationError) ErrorName() string { return "ExternalLinkValidationError" }

// Error satisfies the builtin error interface
func (e ExternalLinkValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sExternalLink.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ExternalLinkValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ExternalLinkValidationError{}
