// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.29.1
// 	protoc        v3.21.10
// source: prodvana/stat/efficiency.proto

package stat

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EfficiencyStat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// how many lines did Prodvana save you from writing? Computed by comparing materialized yaml to proto text format
	SavedLines int32 `protobuf:"varint,1,opt,name=saved_lines,json=savedLines,proto3" json:"saved_lines,omitempty"`
	// how many lines of materialized config was either added, modified, or deleted?
	MaterializedLines int32 `protobuf:"varint,2,opt,name=materialized_lines,json=materializedLines,proto3" json:"materialized_lines,omitempty"`
}

func (x *EfficiencyStat) Reset() {
	*x = EfficiencyStat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_prodvana_stat_efficiency_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EfficiencyStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EfficiencyStat) ProtoMessage() {}

func (x *EfficiencyStat) ProtoReflect() protoreflect.Message {
	mi := &file_prodvana_stat_efficiency_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EfficiencyStat.ProtoReflect.Descriptor instead.
func (*EfficiencyStat) Descriptor() ([]byte, []int) {
	return file_prodvana_stat_efficiency_proto_rawDescGZIP(), []int{0}
}

func (x *EfficiencyStat) GetSavedLines() int32 {
	if x != nil {
		return x.SavedLines
	}
	return 0
}

func (x *EfficiencyStat) GetMaterializedLines() int32 {
	if x != nil {
		return x.MaterializedLines
	}
	return 0
}

var File_prodvana_stat_efficiency_proto protoreflect.FileDescriptor

var file_prodvana_stat_efficiency_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x70, 0x72, 0x6f, 0x64, 0x76, 0x61, 0x6e, 0x61, 0x2f, 0x73, 0x74, 0x61, 0x74, 0x2f,
	0x65, 0x66, 0x66, 0x69, 0x63, 0x69, 0x65, 0x6e, 0x63, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0d, 0x70, 0x72, 0x6f, 0x64, 0x76, 0x61, 0x6e, 0x61, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x22,
	0x60, 0x0a, 0x0e, 0x45, 0x66, 0x66, 0x69, 0x63, 0x69, 0x65, 0x6e, 0x63, 0x79, 0x53, 0x74, 0x61,
	0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x61, 0x76, 0x65, 0x64, 0x5f, 0x6c, 0x69, 0x6e, 0x65, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x73, 0x61, 0x76, 0x65, 0x64, 0x4c, 0x69, 0x6e,
	0x65, 0x73, 0x12, 0x2d, 0x0a, 0x12, 0x6d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x69, 0x7a,
	0x65, 0x64, 0x5f, 0x6c, 0x69, 0x6e, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x11,
	0x6d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x64, 0x4c, 0x69, 0x6e, 0x65,
	0x73, 0x42, 0x49, 0x5a, 0x47, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x70, 0x72, 0x6f, 0x64, 0x76, 0x61, 0x6e, 0x61, 0x2f, 0x70, 0x72, 0x6f, 0x64, 0x76, 0x61, 0x6e,
	0x61, 0x2d, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2f, 0x67, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x64,
	0x76, 0x61, 0x6e, 0x61, 0x2d, 0x73, 0x64, 0x6b, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70,
	0x72, 0x6f, 0x64, 0x76, 0x61, 0x6e, 0x61, 0x2f, 0x73, 0x74, 0x61, 0x74, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_prodvana_stat_efficiency_proto_rawDescOnce sync.Once
	file_prodvana_stat_efficiency_proto_rawDescData = file_prodvana_stat_efficiency_proto_rawDesc
)

func file_prodvana_stat_efficiency_proto_rawDescGZIP() []byte {
	file_prodvana_stat_efficiency_proto_rawDescOnce.Do(func() {
		file_prodvana_stat_efficiency_proto_rawDescData = protoimpl.X.CompressGZIP(file_prodvana_stat_efficiency_proto_rawDescData)
	})
	return file_prodvana_stat_efficiency_proto_rawDescData
}

var file_prodvana_stat_efficiency_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_prodvana_stat_efficiency_proto_goTypes = []interface{}{
	(*EfficiencyStat)(nil), // 0: prodvana.stat.EfficiencyStat
}
var file_prodvana_stat_efficiency_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_prodvana_stat_efficiency_proto_init() }
func file_prodvana_stat_efficiency_proto_init() {
	if File_prodvana_stat_efficiency_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_prodvana_stat_efficiency_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EfficiencyStat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_prodvana_stat_efficiency_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_prodvana_stat_efficiency_proto_goTypes,
		DependencyIndexes: file_prodvana_stat_efficiency_proto_depIdxs,
		MessageInfos:      file_prodvana_stat_efficiency_proto_msgTypes,
	}.Build()
	File_prodvana_stat_efficiency_proto = out.File
	file_prodvana_stat_efficiency_proto_rawDesc = nil
	file_prodvana_stat_efficiency_proto_goTypes = nil
	file_prodvana_stat_efficiency_proto_depIdxs = nil
}
