// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.29.1
// 	protoc        v3.21.10
// source: prodvana/agent/agent_interaction.proto

package agent

import (
	_ "google.golang.org/genproto/googleapis/api/visibility"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InformerAction int32

const (
	InformerAction_ADD    InformerAction = 0
	InformerAction_UPDATE InformerAction = 1
	InformerAction_DELETE InformerAction = 2
)

// Enum value maps for InformerAction.
var (
	InformerAction_name = map[int32]string{
		0: "ADD",
		1: "UPDATE",
		2: "DELETE",
	}
	InformerAction_value = map[string]int32{
		"ADD":    0,
		"UPDATE": 1,
		"DELETE": 2,
	}
)

func (x InformerAction) Enum() *InformerAction {
	p := new(InformerAction)
	*p = x
	return p
}

func (x InformerAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InformerAction) Descriptor() protoreflect.EnumDescriptor {
	return file_prodvana_agent_agent_interaction_proto_enumTypes[0].Descriptor()
}

func (InformerAction) Type() protoreflect.EnumType {
	return &file_prodvana_agent_agent_interaction_proto_enumTypes[0]
}

func (x InformerAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InformerAction.Descriptor instead.
func (InformerAction) EnumDescriptor() ([]byte, []int) {
	return file_prodvana_agent_agent_interaction_proto_rawDescGZIP(), []int{0}
}

type RecordPushCompleteReq_Type int32

const (
	RecordPushCompleteReq_UNKNOWN     RecordPushCompleteReq_Type = 0
	RecordPushCompleteReq_SUCCEEDED   RecordPushCompleteReq_Type = 1
	RecordPushCompleteReq_ROLLED_BACK RecordPushCompleteReq_Type = 2
)

// Enum value maps for RecordPushCompleteReq_Type.
var (
	RecordPushCompleteReq_Type_name = map[int32]string{
		0: "UNKNOWN",
		1: "SUCCEEDED",
		2: "ROLLED_BACK",
	}
	RecordPushCompleteReq_Type_value = map[string]int32{
		"UNKNOWN":     0,
		"SUCCEEDED":   1,
		"ROLLED_BACK": 2,
	}
)

func (x RecordPushCompleteReq_Type) Enum() *RecordPushCompleteReq_Type {
	p := new(RecordPushCompleteReq_Type)
	*p = x
	return p
}

func (x RecordPushCompleteReq_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RecordPushCompleteReq_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_prodvana_agent_agent_interaction_proto_enumTypes[1].Descriptor()
}

func (RecordPushCompleteReq_Type) Type() protoreflect.EnumType {
	return &file_prodvana_agent_agent_interaction_proto_enumTypes[1]
}

func (x RecordPushCompleteReq_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RecordPushCompleteReq_Type.Descriptor instead.
func (RecordPushCompleteReq_Type) EnumDescriptor() ([]byte, []int) {
	return file_prodvana_agent_agent_interaction_proto_rawDescGZIP(), []int{8, 0}
}

type ProxyAPIServerResp_Type int32

const (
	ProxyAPIServerResp_UNKNOWN         ProxyAPIServerResp_Type = 0
	ProxyAPIServerResp_PROXY_APISERVER ProxyAPIServerResp_Type = 1 // More operations like docker registry interactions
)

// Enum value maps for ProxyAPIServerResp_Type.
var (
	ProxyAPIServerResp_Type_name = map[int32]string{
		0: "UNKNOWN",
		1: "PROXY_APISERVER",
	}
	ProxyAPIServerResp_Type_value = map[string]int32{
		"UNKNOWN":         0,
		"PROXY_APISERVER": 1,
	}
)

func (x ProxyAPIServerResp_Type) Enum() *ProxyAPIServerResp_Type {
	p := new(ProxyAPIServerResp_Type)
	*p = x
	return p
}

func (x ProxyAPIServerResp_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProxyAPIServerResp_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_prodvana_agent_agent_interaction_proto_enumTypes[2].Descriptor()
}

func (ProxyAPIServerResp_Type) Type() protoreflect.EnumType {
	return &file_prodvana_agent_agent_interaction_proto_enumTypes[2]
}

func (x ProxyAPIServerResp_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProxyAPIServerResp_Type.Descriptor instead.
func (ProxyAPIServerResp_Type) EnumDescriptor() ([]byte, []int) {
	return file_prodvana_agent_agent_interaction_proto_rawDescGZIP(), []int{21, 0}
}

type HeartbeatReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClusterId string `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"` // TODO(naphat) there needs to be some auth/id for agent
}

func (x *HeartbeatReq) Reset() {
	*x = HeartbeatReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_prodvana_agent_agent_interaction_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeartbeatReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatReq) ProtoMessage() {}

func (x *HeartbeatReq) ProtoReflect() protoreflect.Message {
	mi := &file_prodvana_agent_agent_interaction_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatReq.ProtoReflect.Descriptor instead.
func (*HeartbeatReq) Descriptor() ([]byte, []int) {
	return file_prodvana_agent_agent_interaction_proto_rawDescGZIP(), []int{0}
}

func (x *HeartbeatReq) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

type HeartbeatResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *HeartbeatResp) Reset() {
	*x = HeartbeatResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_prodvana_agent_agent_interaction_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeartbeatResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResp) ProtoMessage() {}

func (x *HeartbeatResp) ProtoReflect() protoreflect.Message {
	mi := &file_prodvana_agent_agent_interaction_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResp.ProtoReflect.Descriptor instead.
func (*HeartbeatResp) Descriptor() ([]byte, []int) {
	return file_prodvana_agent_agent_interaction_proto_rawDescGZIP(), []int{1}
}

type RecordNewUnknownPushReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReleaseChannelId  string                 `protobuf:"bytes,1,opt,name=release_channel_id,json=releaseChannelId,proto3" json:"release_channel_id,omitempty"`
	ServiceId         string                 `protobuf:"bytes,2,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	ClusterId         string                 `protobuf:"bytes,3,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	CreationTimestamp *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=creation_timestamp,json=creationTimestamp,proto3" json:"creation_timestamp,omitempty"`
}

func (x *RecordNewUnknownPushReq) Reset() {
	*x = RecordNewUnknownPushReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_prodvana_agent_agent_interaction_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecordNewUnknownPushReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordNewUnknownPushReq) ProtoMessage() {}

func (x *RecordNewUnknownPushReq) ProtoReflect() protoreflect.Message {
	mi := &file_prodvana_agent_agent_interaction_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordNewUnknownPushReq.ProtoReflect.Descriptor instead.
func (*RecordNewUnknownPushReq) Descriptor() ([]byte, []int) {
	return file_prodvana_agent_agent_interaction_proto_rawDescGZIP(), []int{2}
}

func (x *RecordNewUnknownPushReq) GetReleaseChannelId() string {
	if x != nil {
		return x.ReleaseChannelId
	}
	return ""
}

func (x *RecordNewUnknownPushReq) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *RecordNewUnknownPushReq) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *RecordNewUnknownPushReq) GetCreationTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.CreationTimestamp
	}
	return nil
}

type RecordNewUnknownPushResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RecordNewUnknownPushResp) Reset() {
	*x = RecordNewUnknownPushResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_prodvana_agent_agent_interaction_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecordNewUnknownPushResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordNewUnknownPushResp) ProtoMessage() {}

func (x *RecordNewUnknownPushResp) ProtoReflect() protoreflect.Message {
	mi := &file_prodvana_agent_agent_interaction_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordNewUnknownPushResp.ProtoReflect.Descriptor instead.
func (*RecordNewUnknownPushResp) Descriptor() ([]byte, []int) {
	return file_prodvana_agent_agent_interaction_proto_rawDescGZIP(), []int{3}
}

type RecordPushStartReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReleaseChannelId  string                 `protobuf:"bytes,1,opt,name=release_channel_id,json=releaseChannelId,proto3" json:"release_channel_id,omitempty"`
	ServiceId         string                 `protobuf:"bytes,2,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	CreationTimestamp *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=creation_timestamp,json=creationTimestamp,proto3" json:"creation_timestamp,omitempty"`
	ClusterId         string                 `protobuf:"bytes,3,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	StartTimestamp    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=start_timestamp,json=startTimestamp,proto3" json:"start_timestamp,omitempty"`
}

func (x *RecordPushStartReq) Reset() {
	*x = RecordPushStartReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_prodvana_agent_agent_interaction_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecordPushStartReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordPushStartReq) ProtoMessage() {}

func (x *RecordPushStartReq) ProtoReflect() protoreflect.Message {
	mi := &file_prodvana_agent_agent_interaction_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordPushStartReq.ProtoReflect.Descriptor instead.
func (*RecordPushStartReq) Descriptor() ([]byte, []int) {
	return file_prodvana_agent_agent_interaction_proto_rawDescGZIP(), []int{4}
}

func (x *RecordPushStartReq) GetReleaseChannelId() string {
	if x != nil {
		return x.ReleaseChannelId
	}
	return ""
}

func (x *RecordPushStartReq) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *RecordPushStartReq) GetCreationTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.CreationTimestamp
	}
	return nil
}

func (x *RecordPushStartReq) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *RecordPushStartReq) GetStartTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTimestamp
	}
	return nil
}

type RecordPushStartResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RecordPushStartResp) Reset() {
	*x = RecordPushStartResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_prodvana_agent_agent_interaction_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecordPushStartResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordPushStartResp) ProtoMessage() {}

func (x *RecordPushStartResp) ProtoReflect() protoreflect.Message {
	mi := &file_prodvana_agent_agent_interaction_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordPushStartResp.ProtoReflect.Descriptor instead.
func (*RecordPushStartResp) Descriptor() ([]byte, []int) {
	return file_prodvana_agent_agent_interaction_proto_rawDescGZIP(), []int{5}
}

type RecordPushOngoingReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReleaseChannelId  string                 `protobuf:"bytes,1,opt,name=release_channel_id,json=releaseChannelId,proto3" json:"release_channel_id,omitempty"`
	ServiceId         string                 `protobuf:"bytes,2,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	CreationTimestamp *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=creation_timestamp,json=creationTimestamp,proto3" json:"creation_timestamp,omitempty"`
	ClusterId         string                 `protobuf:"bytes,3,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
}

func (x *RecordPushOngoingReq) Reset() {
	*x = RecordPushOngoingReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_prodvana_agent_agent_interaction_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecordPushOngoingReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordPushOngoingReq) ProtoMessage() {}

func (x *RecordPushOngoingReq) ProtoReflect() protoreflect.Message {
	mi := &file_prodvana_agent_agent_interaction_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordPushOngoingReq.ProtoReflect.Descriptor instead.
func (*RecordPushOngoingReq) Descriptor() ([]byte, []int) {
	return file_prodvana_agent_agent_interaction_proto_rawDescGZIP(), []int{6}
}

func (x *RecordPushOngoingReq) GetReleaseChannelId() string {
	if x != nil {
		return x.ReleaseChannelId
	}
	return ""
}

func (x *RecordPushOngoingReq) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *RecordPushOngoingReq) GetCreationTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.CreationTimestamp
	}
	return nil
}

func (x *RecordPushOngoingReq) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

type RecordPushOngoingResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RecordPushOngoingResp) Reset() {
	*x = RecordPushOngoingResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_prodvana_agent_agent_interaction_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecordPushOngoingResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordPushOngoingResp) ProtoMessage() {}

func (x *RecordPushOngoingResp) ProtoReflect() protoreflect.Message {
	mi := &file_prodvana_agent_agent_interaction_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordPushOngoingResp.ProtoReflect.Descriptor instead.
func (*RecordPushOngoingResp) Descriptor() ([]byte, []int) {
	return file_prodvana_agent_agent_interaction_proto_rawDescGZIP(), []int{7}
}

type RecordPushCompleteReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReleaseChannelId  string                     `protobuf:"bytes,1,opt,name=release_channel_id,json=releaseChannelId,proto3" json:"release_channel_id,omitempty"`
	ServiceId         string                     `protobuf:"bytes,2,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	CreationTimestamp *timestamppb.Timestamp     `protobuf:"bytes,5,opt,name=creation_timestamp,json=creationTimestamp,proto3" json:"creation_timestamp,omitempty"`
	ClusterId         string                     `protobuf:"bytes,3,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	Type              RecordPushCompleteReq_Type `protobuf:"varint,4,opt,name=type,proto3,enum=prodvana.agent.RecordPushCompleteReq_Type" json:"type,omitempty"`
}

func (x *RecordPushCompleteReq) Reset() {
	*x = RecordPushCompleteReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_prodvana_agent_agent_interaction_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecordPushCompleteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordPushCompleteReq) ProtoMessage() {}

func (x *RecordPushCompleteReq) ProtoReflect() protoreflect.Message {
	mi := &file_prodvana_agent_agent_interaction_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordPushCompleteReq.ProtoReflect.Descriptor instead.
func (*RecordPushCompleteReq) Descriptor() ([]byte, []int) {
	return file_prodvana_agent_agent_interaction_proto_rawDescGZIP(), []int{8}
}

func (x *RecordPushCompleteReq) GetReleaseChannelId() string {
	if x != nil {
		return x.ReleaseChannelId
	}
	return ""
}

func (x *RecordPushCompleteReq) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *RecordPushCompleteReq) GetCreationTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.CreationTimestamp
	}
	return nil
}

func (x *RecordPushCompleteReq) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *RecordPushCompleteReq) GetType() RecordPushCompleteReq_Type {
	if x != nil {
		return x.Type
	}
	return RecordPushCompleteReq_UNKNOWN
}

type RecordPushCompleteResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RecordPushCompleteResp) Reset() {
	*x = RecordPushCompleteResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_prodvana_agent_agent_interaction_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecordPushCompleteResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordPushCompleteResp) ProtoMessage() {}

func (x *RecordPushCompleteResp) ProtoReflect() protoreflect.Message {
	mi := &file_prodvana_agent_agent_interaction_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordPushCompleteResp.ProtoReflect.Descriptor instead.
func (*RecordPushCompleteResp) Descriptor() ([]byte, []int) {
	return file_prodvana_agent_agent_interaction_proto_rawDescGZIP(), []int{9}
}

type ConfirmPushApprovalReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReleaseChannelId  string                 `protobuf:"bytes,1,opt,name=release_channel_id,json=releaseChannelId,proto3" json:"release_channel_id,omitempty"`
	ServiceId         string                 `protobuf:"bytes,2,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	CreationTimestamp *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=creation_timestamp,json=creationTimestamp,proto3" json:"creation_timestamp,omitempty"`
	ClusterId         string                 `protobuf:"bytes,3,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
}

func (x *ConfirmPushApprovalReq) Reset() {
	*x = ConfirmPushApprovalReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_prodvana_agent_agent_interaction_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfirmPushApprovalReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmPushApprovalReq) ProtoMessage() {}

func (x *ConfirmPushApprovalReq) ProtoReflect() protoreflect.Message {
	mi := &file_prodvana_agent_agent_interaction_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmPushApprovalReq.ProtoReflect.Descriptor instead.
func (*ConfirmPushApprovalReq) Descriptor() ([]byte, []int) {
	return file_prodvana_agent_agent_interaction_proto_rawDescGZIP(), []int{10}
}

func (x *ConfirmPushApprovalReq) GetReleaseChannelId() string {
	if x != nil {
		return x.ReleaseChannelId
	}
	return ""
}

func (x *ConfirmPushApprovalReq) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *ConfirmPushApprovalReq) GetCreationTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.CreationTimestamp
	}
	return nil
}

func (x *ConfirmPushApprovalReq) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

type ConfirmPushApprovalResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Approved bool `protobuf:"varint,1,opt,name=approved,proto3" json:"approved,omitempty"`
}

func (x *ConfirmPushApprovalResp) Reset() {
	*x = ConfirmPushApprovalResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_prodvana_agent_agent_interaction_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfirmPushApprovalResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmPushApprovalResp) ProtoMessage() {}

func (x *ConfirmPushApprovalResp) ProtoReflect() protoreflect.Message {
	mi := &file_prodvana_agent_agent_interaction_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmPushApprovalResp.ProtoReflect.Descriptor instead.
func (*ConfirmPushApprovalResp) Descriptor() ([]byte, []int) {
	return file_prodvana_agent_agent_interaction_proto_rawDescGZIP(), []int{11}
}

func (x *ConfirmPushApprovalResp) GetApproved() bool {
	if x != nil {
		return x.Approved
	}
	return false
}

type RecordPodReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pod       []byte         `protobuf:"bytes,1,opt,name=pod,proto3" json:"pod,omitempty"`
	Action    InformerAction `protobuf:"varint,2,opt,name=action,proto3,enum=prodvana.agent.InformerAction" json:"action,omitempty"`
	RuntimeId string         `protobuf:"bytes,3,opt,name=runtime_id,json=runtimeId,proto3" json:"runtime_id,omitempty"`
}

func (x *RecordPodReq) Reset() {
	*x = RecordPodReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_prodvana_agent_agent_interaction_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecordPodReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordPodReq) ProtoMessage() {}

func (x *RecordPodReq) ProtoReflect() protoreflect.Message {
	mi := &file_prodvana_agent_agent_interaction_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordPodReq.ProtoReflect.Descriptor instead.
func (*RecordPodReq) Descriptor() ([]byte, []int) {
	return file_prodvana_agent_agent_interaction_proto_rawDescGZIP(), []int{12}
}

func (x *RecordPodReq) GetPod() []byte {
	if x != nil {
		return x.Pod
	}
	return nil
}

func (x *RecordPodReq) GetAction() InformerAction {
	if x != nil {
		return x.Action
	}
	return InformerAction_ADD
}

func (x *RecordPodReq) GetRuntimeId() string {
	if x != nil {
		return x.RuntimeId
	}
	return ""
}

type RecordPodResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RecordPodResp) Reset() {
	*x = RecordPodResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_prodvana_agent_agent_interaction_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecordPodResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordPodResp) ProtoMessage() {}

func (x *RecordPodResp) ProtoReflect() protoreflect.Message {
	mi := &file_prodvana_agent_agent_interaction_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordPodResp.ProtoReflect.Descriptor instead.
func (*RecordPodResp) Descriptor() ([]byte, []int) {
	return file_prodvana_agent_agent_interaction_proto_rawDescGZIP(), []int{13}
}

type RecordPodsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pods      [][]byte `protobuf:"bytes,1,rep,name=pods,proto3" json:"pods,omitempty"`
	RuntimeId string   `protobuf:"bytes,2,opt,name=runtime_id,json=runtimeId,proto3" json:"runtime_id,omitempty"`
}

func (x *RecordPodsReq) Reset() {
	*x = RecordPodsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_prodvana_agent_agent_interaction_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecordPodsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordPodsReq) ProtoMessage() {}

func (x *RecordPodsReq) ProtoReflect() protoreflect.Message {
	mi := &file_prodvana_agent_agent_interaction_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordPodsReq.ProtoReflect.Descriptor instead.
func (*RecordPodsReq) Descriptor() ([]byte, []int) {
	return file_prodvana_agent_agent_interaction_proto_rawDescGZIP(), []int{14}
}

func (x *RecordPodsReq) GetPods() [][]byte {
	if x != nil {
		return x.Pods
	}
	return nil
}

func (x *RecordPodsReq) GetRuntimeId() string {
	if x != nil {
		return x.RuntimeId
	}
	return ""
}

type RecordPodsResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RecordPodsResp) Reset() {
	*x = RecordPodsResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_prodvana_agent_agent_interaction_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecordPodsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordPodsResp) ProtoMessage() {}

func (x *RecordPodsResp) ProtoReflect() protoreflect.Message {
	mi := &file_prodvana_agent_agent_interaction_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordPodsResp.ProtoReflect.Descriptor instead.
func (*RecordPodsResp) Descriptor() ([]byte, []int) {
	return file_prodvana_agent_agent_interaction_proto_rawDescGZIP(), []int{15}
}

type RecordDeploymentReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Deployment []byte         `protobuf:"bytes,1,opt,name=deployment,proto3" json:"deployment,omitempty"`
	Action     InformerAction `protobuf:"varint,2,opt,name=action,proto3,enum=prodvana.agent.InformerAction" json:"action,omitempty"`
}

func (x *RecordDeploymentReq) Reset() {
	*x = RecordDeploymentReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_prodvana_agent_agent_interaction_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecordDeploymentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordDeploymentReq) ProtoMessage() {}

func (x *RecordDeploymentReq) ProtoReflect() protoreflect.Message {
	mi := &file_prodvana_agent_agent_interaction_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordDeploymentReq.ProtoReflect.Descriptor instead.
func (*RecordDeploymentReq) Descriptor() ([]byte, []int) {
	return file_prodvana_agent_agent_interaction_proto_rawDescGZIP(), []int{16}
}

func (x *RecordDeploymentReq) GetDeployment() []byte {
	if x != nil {
		return x.Deployment
	}
	return nil
}

func (x *RecordDeploymentReq) GetAction() InformerAction {
	if x != nil {
		return x.Action
	}
	return InformerAction_ADD
}

type RecordDeploymentResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PushTimestamp *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=push_timestamp,json=pushTimestamp,proto3" json:"push_timestamp,omitempty"`
}

func (x *RecordDeploymentResp) Reset() {
	*x = RecordDeploymentResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_prodvana_agent_agent_interaction_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecordDeploymentResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordDeploymentResp) ProtoMessage() {}

func (x *RecordDeploymentResp) ProtoReflect() protoreflect.Message {
	mi := &file_prodvana_agent_agent_interaction_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordDeploymentResp.ProtoReflect.Descriptor instead.
func (*RecordDeploymentResp) Descriptor() ([]byte, []int) {
	return file_prodvana_agent_agent_interaction_proto_rawDescGZIP(), []int{17}
}

func (x *RecordDeploymentResp) GetPushTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.PushTimestamp
	}
	return nil
}

type RecordRolloutReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rollout []byte         `protobuf:"bytes,1,opt,name=rollout,proto3" json:"rollout,omitempty"`
	Action  InformerAction `protobuf:"varint,2,opt,name=action,proto3,enum=prodvana.agent.InformerAction" json:"action,omitempty"`
}

func (x *RecordRolloutReq) Reset() {
	*x = RecordRolloutReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_prodvana_agent_agent_interaction_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecordRolloutReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordRolloutReq) ProtoMessage() {}

func (x *RecordRolloutReq) ProtoReflect() protoreflect.Message {
	mi := &file_prodvana_agent_agent_interaction_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordRolloutReq.ProtoReflect.Descriptor instead.
func (*RecordRolloutReq) Descriptor() ([]byte, []int) {
	return file_prodvana_agent_agent_interaction_proto_rawDescGZIP(), []int{18}
}

func (x *RecordRolloutReq) GetRollout() []byte {
	if x != nil {
		return x.Rollout
	}
	return nil
}

func (x *RecordRolloutReq) GetAction() InformerAction {
	if x != nil {
		return x.Action
	}
	return InformerAction_ADD
}

type RecordRolloutResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PushTimestamp *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=push_timestamp,json=pushTimestamp,proto3" json:"push_timestamp,omitempty"`
}

func (x *RecordRolloutResp) Reset() {
	*x = RecordRolloutResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_prodvana_agent_agent_interaction_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecordRolloutResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordRolloutResp) ProtoMessage() {}

func (x *RecordRolloutResp) ProtoReflect() protoreflect.Message {
	mi := &file_prodvana_agent_agent_interaction_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordRolloutResp.ProtoReflect.Descriptor instead.
func (*RecordRolloutResp) Descriptor() ([]byte, []int) {
	return file_prodvana_agent_agent_interaction_proto_rawDescGZIP(), []int{19}
}

func (x *RecordRolloutResp) GetPushTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.PushTimestamp
	}
	return nil
}

type ProxyAPIServerReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Msg:
	//
	//	*ProxyAPIServerReq_RuntimeId
	//	*ProxyAPIServerReq_Blob
	Msg isProxyAPIServerReq_Msg `protobuf_oneof:"msg"`
	// Debugging/logging bits
	ConnId string `protobuf:"bytes,3,opt,name=conn_id,json=connId,proto3" json:"conn_id,omitempty"`
}

func (x *ProxyAPIServerReq) Reset() {
	*x = ProxyAPIServerReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_prodvana_agent_agent_interaction_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProxyAPIServerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyAPIServerReq) ProtoMessage() {}

func (x *ProxyAPIServerReq) ProtoReflect() protoreflect.Message {
	mi := &file_prodvana_agent_agent_interaction_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyAPIServerReq.ProtoReflect.Descriptor instead.
func (*ProxyAPIServerReq) Descriptor() ([]byte, []int) {
	return file_prodvana_agent_agent_interaction_proto_rawDescGZIP(), []int{20}
}

func (m *ProxyAPIServerReq) GetMsg() isProxyAPIServerReq_Msg {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (x *ProxyAPIServerReq) GetRuntimeId() string {
	if x, ok := x.GetMsg().(*ProxyAPIServerReq_RuntimeId); ok {
		return x.RuntimeId
	}
	return ""
}

func (x *ProxyAPIServerReq) GetBlob() []byte {
	if x, ok := x.GetMsg().(*ProxyAPIServerReq_Blob); ok {
		return x.Blob
	}
	return nil
}

func (x *ProxyAPIServerReq) GetConnId() string {
	if x != nil {
		return x.ConnId
	}
	return ""
}

type isProxyAPIServerReq_Msg interface {
	isProxyAPIServerReq_Msg()
}

type ProxyAPIServerReq_RuntimeId struct {
	RuntimeId string `protobuf:"bytes,1,opt,name=runtime_id,json=runtimeId,proto3,oneof"` // Header
}

type ProxyAPIServerReq_Blob struct {
	Blob []byte `protobuf:"bytes,2,opt,name=blob,proto3,oneof"` // Everything after header
}

func (*ProxyAPIServerReq_RuntimeId) isProxyAPIServerReq_Msg() {}

func (*ProxyAPIServerReq_Blob) isProxyAPIServerReq_Msg() {}

type ProxyAPIServerResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Msg:
	//
	//	*ProxyAPIServerResp_Type_
	//	*ProxyAPIServerResp_Blob
	Msg isProxyAPIServerResp_Msg `protobuf_oneof:"msg"`
}

func (x *ProxyAPIServerResp) Reset() {
	*x = ProxyAPIServerResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_prodvana_agent_agent_interaction_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProxyAPIServerResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyAPIServerResp) ProtoMessage() {}

func (x *ProxyAPIServerResp) ProtoReflect() protoreflect.Message {
	mi := &file_prodvana_agent_agent_interaction_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyAPIServerResp.ProtoReflect.Descriptor instead.
func (*ProxyAPIServerResp) Descriptor() ([]byte, []int) {
	return file_prodvana_agent_agent_interaction_proto_rawDescGZIP(), []int{21}
}

func (m *ProxyAPIServerResp) GetMsg() isProxyAPIServerResp_Msg {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (x *ProxyAPIServerResp) GetType() ProxyAPIServerResp_Type {
	if x, ok := x.GetMsg().(*ProxyAPIServerResp_Type_); ok {
		return x.Type
	}
	return ProxyAPIServerResp_UNKNOWN
}

func (x *ProxyAPIServerResp) GetBlob() []byte {
	if x, ok := x.GetMsg().(*ProxyAPIServerResp_Blob); ok {
		return x.Blob
	}
	return nil
}

type isProxyAPIServerResp_Msg interface {
	isProxyAPIServerResp_Msg()
}

type ProxyAPIServerResp_Type_ struct {
	Type ProxyAPIServerResp_Type `protobuf:"varint,1,opt,name=type,proto3,enum=prodvana.agent.ProxyAPIServerResp_Type,oneof"` // Header
}

type ProxyAPIServerResp_Blob struct {
	Blob []byte `protobuf:"bytes,2,opt,name=blob,proto3,oneof"`
}

func (*ProxyAPIServerResp_Type_) isProxyAPIServerResp_Msg() {}

func (*ProxyAPIServerResp_Blob) isProxyAPIServerResp_Msg() {}

type DebugInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error            string `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"` // set only if there's any error running debug commands
	TcptracerouteOut string `protobuf:"bytes,2,opt,name=tcptraceroute_out,json=tcptracerouteOut,proto3" json:"tcptraceroute_out,omitempty"`
}

func (x *DebugInfo) Reset() {
	*x = DebugInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_prodvana_agent_agent_interaction_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DebugInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebugInfo) ProtoMessage() {}

func (x *DebugInfo) ProtoReflect() protoreflect.Message {
	mi := &file_prodvana_agent_agent_interaction_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DebugInfo.ProtoReflect.Descriptor instead.
func (*DebugInfo) Descriptor() ([]byte, []int) {
	return file_prodvana_agent_agent_interaction_proto_rawDescGZIP(), []int{22}
}

func (x *DebugInfo) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *DebugInfo) GetTcptracerouteOut() string {
	if x != nil {
		return x.TcptracerouteOut
	}
	return ""
}

type ReportDebugInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RuntimeId string     `protobuf:"bytes,1,opt,name=runtime_id,json=runtimeId,proto3" json:"runtime_id,omitempty"`
	Info      *DebugInfo `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
}

func (x *ReportDebugInfoReq) Reset() {
	*x = ReportDebugInfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_prodvana_agent_agent_interaction_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReportDebugInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportDebugInfoReq) ProtoMessage() {}

func (x *ReportDebugInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_prodvana_agent_agent_interaction_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportDebugInfoReq.ProtoReflect.Descriptor instead.
func (*ReportDebugInfoReq) Descriptor() ([]byte, []int) {
	return file_prodvana_agent_agent_interaction_proto_rawDescGZIP(), []int{23}
}

func (x *ReportDebugInfoReq) GetRuntimeId() string {
	if x != nil {
		return x.RuntimeId
	}
	return ""
}

func (x *ReportDebugInfoReq) GetInfo() *DebugInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type ReportDebugInfoResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReportDebugInfoResp) Reset() {
	*x = ReportDebugInfoResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_prodvana_agent_agent_interaction_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReportDebugInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportDebugInfoResp) ProtoMessage() {}

func (x *ReportDebugInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_prodvana_agent_agent_interaction_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportDebugInfoResp.ProtoReflect.Descriptor instead.
func (*ReportDebugInfoResp) Descriptor() ([]byte, []int) {
	return file_prodvana_agent_agent_interaction_proto_rawDescGZIP(), []int{24}
}

var File_prodvana_agent_agent_interaction_proto protoreflect.FileDescriptor

var file_prodvana_agent_agent_interaction_proto_rawDesc = []byte{
	0x0a, 0x26, 0x70, 0x72, 0x6f, 0x64, 0x76, 0x61, 0x6e, 0x61, 0x2f, 0x61, 0x67, 0x65, 0x6e, 0x74,
	0x2f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x70, 0x72, 0x6f, 0x64, 0x76, 0x61,
	0x6e, 0x61, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x69, 0x73, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2d, 0x0a, 0x0c, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62,
	0x65, 0x61, 0x74, 0x52, 0x65, 0x71, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x6c, 0x75, 0x73,
	0x74, 0x65, 0x72, 0x49, 0x64, 0x22, 0x0f, 0x0a, 0x0d, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65,
	0x61, 0x74, 0x52, 0x65, 0x73, 0x70, 0x22, 0xd0, 0x01, 0x0a, 0x17, 0x52, 0x65, 0x63, 0x6f, 0x72,
	0x64, 0x4e, 0x65, 0x77, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x50, 0x75, 0x73, 0x68, 0x52,
	0x65, 0x71, 0x12, 0x2c, 0x0a, 0x12, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x5f, 0x63, 0x68,
	0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10,
	0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x64,
	0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x12,
	0x1d, 0x0a, 0x0a, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x49, 0x64, 0x12, 0x49,
	0x0a, 0x12, 0x63, 0x72, 0x65, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x11, 0x63, 0x72, 0x65, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x1a, 0x0a, 0x18, 0x52, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x4e, 0x65, 0x77, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x50, 0x75, 0x73,
	0x68, 0x52, 0x65, 0x73, 0x70, 0x22, 0x90, 0x02, 0x0a, 0x12, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x50, 0x75, 0x73, 0x68, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x12, 0x2c, 0x0a, 0x12,
	0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x5f, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73,
	0x65, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x12, 0x49, 0x0a, 0x12, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x52, 0x11, 0x63, 0x72, 0x65, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x43, 0x0a, 0x0f, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0e, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x15, 0x0a, 0x13, 0x52, 0x65, 0x63, 0x6f,
	0x72, 0x64, 0x50, 0x75, 0x73, 0x68, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x22,
	0xcd, 0x01, 0x0a, 0x14, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x50, 0x75, 0x73, 0x68, 0x4f, 0x6e,
	0x67, 0x6f, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x12, 0x2c, 0x0a, 0x12, 0x72, 0x65, 0x6c, 0x65,
	0x61, 0x73, 0x65, 0x5f, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x43, 0x68, 0x61,
	0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x49, 0x64, 0x12, 0x49, 0x0a, 0x12, 0x63, 0x72, 0x65, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x11, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x49, 0x64, 0x22,
	0x17, 0x0a, 0x15, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x50, 0x75, 0x73, 0x68, 0x4f, 0x6e, 0x67,
	0x6f, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x22, 0xc3, 0x02, 0x0a, 0x15, 0x52, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x50, 0x75, 0x73, 0x68, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x52,
	0x65, 0x71, 0x12, 0x2c, 0x0a, 0x12, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x5f, 0x63, 0x68,
	0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10,
	0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x64,
	0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x12,
	0x49, 0x0a, 0x12, 0x63, 0x72, 0x65, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x11, 0x63, 0x72, 0x65, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x6c,
	0x75, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x49, 0x64, 0x12, 0x3e, 0x0a, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2a, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x76, 0x61,
	0x6e, 0x61, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x50,
	0x75, 0x73, 0x68, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x2e, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x33, 0x0a, 0x04, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x0d,
	0x0a, 0x09, 0x53, 0x55, 0x43, 0x43, 0x45, 0x45, 0x44, 0x45, 0x44, 0x10, 0x01, 0x12, 0x0f, 0x0a,
	0x0b, 0x52, 0x4f, 0x4c, 0x4c, 0x45, 0x44, 0x5f, 0x42, 0x41, 0x43, 0x4b, 0x10, 0x02, 0x22, 0x18,
	0x0a, 0x16, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x50, 0x75, 0x73, 0x68, 0x43, 0x6f, 0x6d, 0x70,
	0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x22, 0xcf, 0x01, 0x0a, 0x16, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x72, 0x6d, 0x50, 0x75, 0x73, 0x68, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x61, 0x6c,
	0x52, 0x65, 0x71, 0x12, 0x2c, 0x0a, 0x12, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x5f, 0x63,
	0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x10, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x49,
	0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64,
	0x12, 0x49, 0x0a, 0x12, 0x63, 0x72, 0x65, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x11, 0x63, 0x72, 0x65, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x1d, 0x0a, 0x0a, 0x63,
	0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x49, 0x64, 0x22, 0x35, 0x0a, 0x17, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x72, 0x6d, 0x50, 0x75, 0x73, 0x68, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x61,
	0x6c, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x65,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x61, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x65,
	0x64, 0x22, 0x77, 0x0a, 0x0c, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x50, 0x6f, 0x64, 0x52, 0x65,
	0x71, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x6f, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03,
	0x70, 0x6f, 0x64, 0x12, 0x36, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x76, 0x61, 0x6e, 0x61, 0x2e, 0x61,
	0x67, 0x65, 0x6e, 0x74, 0x2e, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x65, 0x72, 0x41, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x72,
	0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x49, 0x64, 0x22, 0x0f, 0x0a, 0x0d, 0x52, 0x65,
	0x63, 0x6f, 0x72, 0x64, 0x50, 0x6f, 0x64, 0x52, 0x65, 0x73, 0x70, 0x22, 0x42, 0x0a, 0x0d, 0x52,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x50, 0x6f, 0x64, 0x73, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04,
	0x70, 0x6f, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x04, 0x70, 0x6f, 0x64, 0x73,
	0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x49, 0x64, 0x22,
	0x10, 0x0a, 0x0e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x50, 0x6f, 0x64, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x22, 0x6d, 0x0a, 0x13, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x44, 0x65, 0x70, 0x6c, 0x6f,
	0x79, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x12, 0x1e, 0x0a, 0x0a, 0x64, 0x65, 0x70, 0x6c,
	0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x64, 0x65,
	0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x36, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x76,
	0x61, 0x6e, 0x61, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d,
	0x65, 0x72, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x22, 0x59, 0x0a, 0x14, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79,
	0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x41, 0x0a, 0x0e, 0x70, 0x75, 0x73, 0x68,
	0x5f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0d, 0x70, 0x75,
	0x73, 0x68, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x64, 0x0a, 0x10, 0x52,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x6f, 0x6c, 0x6c, 0x6f, 0x75, 0x74, 0x52, 0x65, 0x71, 0x12,
	0x18, 0x0a, 0x07, 0x72, 0x6f, 0x6c, 0x6c, 0x6f, 0x75, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x07, 0x72, 0x6f, 0x6c, 0x6c, 0x6f, 0x75, 0x74, 0x12, 0x36, 0x0a, 0x06, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x64,
	0x76, 0x61, 0x6e, 0x61, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x49, 0x6e, 0x66, 0x6f, 0x72,
	0x6d, 0x65, 0x72, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x22, 0x56, 0x0a, 0x11, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x6f, 0x6c, 0x6c, 0x6f,
	0x75, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x41, 0x0a, 0x0e, 0x70, 0x75, 0x73, 0x68, 0x5f, 0x74,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0d, 0x70, 0x75, 0x73, 0x68,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x6a, 0x0a, 0x11, 0x50, 0x72, 0x6f,
	0x78, 0x79, 0x41, 0x50, 0x49, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x1f,
	0x0a, 0x0a, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x48, 0x00, 0x52, 0x09, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x49, 0x64, 0x12,
	0x14, 0x0a, 0x04, 0x62, 0x6c, 0x6f, 0x62, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52,
	0x04, 0x62, 0x6c, 0x6f, 0x62, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x6e, 0x5f, 0x69, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x6f, 0x6e, 0x6e, 0x49, 0x64, 0x42, 0x05,
	0x0a, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x9a, 0x01, 0x0a, 0x12, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x41,
	0x50, 0x49, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x3d, 0x0a, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x27, 0x2e, 0x70, 0x72, 0x6f,
	0x64, 0x76, 0x61, 0x6e, 0x61, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x50, 0x72, 0x6f, 0x78,
	0x79, 0x41, 0x50, 0x49, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x2e, 0x54,
	0x79, 0x70, 0x65, 0x48, 0x00, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x04, 0x62,
	0x6c, 0x6f, 0x62, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x04, 0x62, 0x6c, 0x6f,
	0x62, 0x22, 0x28, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b,
	0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x13, 0x0a, 0x0f, 0x50, 0x52, 0x4f, 0x58, 0x59, 0x5f,
	0x41, 0x50, 0x49, 0x53, 0x45, 0x52, 0x56, 0x45, 0x52, 0x10, 0x01, 0x42, 0x05, 0x0a, 0x03, 0x6d,
	0x73, 0x67, 0x22, 0x4e, 0x0a, 0x09, 0x44, 0x65, 0x62, 0x75, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x2b, 0x0a, 0x11, 0x74, 0x63, 0x70, 0x74, 0x72, 0x61, 0x63,
	0x65, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x5f, 0x6f, 0x75, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x10, 0x74, 0x63, 0x70, 0x74, 0x72, 0x61, 0x63, 0x65, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x4f,
	0x75, 0x74, 0x22, 0x62, 0x0a, 0x12, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x44, 0x65, 0x62, 0x75,
	0x67, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x75, 0x6e, 0x74,
	0x69, 0x6d, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x75,
	0x6e, 0x74, 0x69, 0x6d, 0x65, 0x49, 0x64, 0x12, 0x2d, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x76, 0x61, 0x6e, 0x61,
	0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x44, 0x65, 0x62, 0x75, 0x67, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x22, 0x15, 0x0a, 0x13, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74,
	0x44, 0x65, 0x62, 0x75, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x2a, 0x31, 0x0a,
	0x0e, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x65, 0x72, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x07, 0x0a, 0x03, 0x41, 0x44, 0x44, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x55, 0x50, 0x44, 0x41,
	0x54, 0x45, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x44, 0x45, 0x4c, 0x45, 0x54, 0x45, 0x10, 0x02,
	0x32, 0x81, 0x09, 0x0a, 0x10, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x4a, 0x0a, 0x09, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65,
	0x61, 0x74, 0x12, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x76, 0x61, 0x6e, 0x61, 0x2e, 0x61, 0x67,
	0x65, 0x6e, 0x74, 0x2e, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x52, 0x65, 0x71,
	0x1a, 0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x76, 0x61, 0x6e, 0x61, 0x2e, 0x61, 0x67, 0x65, 0x6e,
	0x74, 0x2e, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70, 0x22,
	0x00, 0x12, 0x68, 0x0a, 0x13, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x50, 0x75, 0x73, 0x68,
	0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x61, 0x6c, 0x12, 0x26, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x76,
	0x61, 0x6e, 0x61, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72,
	0x6d, 0x50, 0x75, 0x73, 0x68, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x61, 0x6c, 0x52, 0x65, 0x71,
	0x1a, 0x27, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x76, 0x61, 0x6e, 0x61, 0x2e, 0x61, 0x67, 0x65, 0x6e,
	0x74, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x50, 0x75, 0x73, 0x68, 0x41, 0x70, 0x70,
	0x72, 0x6f, 0x76, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x6b, 0x0a, 0x14, 0x52,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x4e, 0x65, 0x77, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x50,
	0x75, 0x73, 0x68, 0x12, 0x27, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x76, 0x61, 0x6e, 0x61, 0x2e, 0x61,
	0x67, 0x65, 0x6e, 0x74, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x4e, 0x65, 0x77, 0x55, 0x6e,
	0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x50, 0x75, 0x73, 0x68, 0x52, 0x65, 0x71, 0x1a, 0x28, 0x2e, 0x70,
	0x72, 0x6f, 0x64, 0x76, 0x61, 0x6e, 0x61, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x52, 0x65,
	0x63, 0x6f, 0x72, 0x64, 0x4e, 0x65, 0x77, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x50, 0x75,
	0x73, 0x68, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x5c, 0x0a, 0x0f, 0x52, 0x65, 0x63, 0x6f,
	0x72, 0x64, 0x50, 0x75, 0x73, 0x68, 0x53, 0x74, 0x61, 0x72, 0x74, 0x12, 0x22, 0x2e, 0x70, 0x72,
	0x6f, 0x64, 0x76, 0x61, 0x6e, 0x61, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x52, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x50, 0x75, 0x73, 0x68, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x1a,
	0x23, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x76, 0x61, 0x6e, 0x61, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74,
	0x2e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x50, 0x75, 0x73, 0x68, 0x53, 0x74, 0x61, 0x72, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x62, 0x0a, 0x11, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x50, 0x75, 0x73, 0x68, 0x4f, 0x6e, 0x67, 0x6f, 0x69, 0x6e, 0x67, 0x12, 0x24, 0x2e, 0x70, 0x72,
	0x6f, 0x64, 0x76, 0x61, 0x6e, 0x61, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x52, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x50, 0x75, 0x73, 0x68, 0x4f, 0x6e, 0x67, 0x6f, 0x69, 0x6e, 0x67, 0x52, 0x65,
	0x71, 0x1a, 0x25, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x76, 0x61, 0x6e, 0x61, 0x2e, 0x61, 0x67, 0x65,
	0x6e, 0x74, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x50, 0x75, 0x73, 0x68, 0x4f, 0x6e, 0x67,
	0x6f, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x65, 0x0a, 0x12, 0x52, 0x65,
	0x63, 0x6f, 0x72, 0x64, 0x50, 0x75, 0x73, 0x68, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65,
	0x12, 0x25, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x76, 0x61, 0x6e, 0x61, 0x2e, 0x61, 0x67, 0x65, 0x6e,
	0x74, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x50, 0x75, 0x73, 0x68, 0x43, 0x6f, 0x6d, 0x70,
	0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x26, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x76, 0x61,
	0x6e, 0x61, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x50,
	0x75, 0x73, 0x68, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x22,
	0x00, 0x12, 0x4a, 0x0a, 0x09, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x50, 0x6f, 0x64, 0x12, 0x1c,
	0x2e, 0x70, 0x72, 0x6f, 0x64, 0x76, 0x61, 0x6e, 0x61, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e,
	0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x50, 0x6f, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x1d, 0x2e, 0x70,
	0x72, 0x6f, 0x64, 0x76, 0x61, 0x6e, 0x61, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x52, 0x65,
	0x63, 0x6f, 0x72, 0x64, 0x50, 0x6f, 0x64, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x4d, 0x0a,
	0x0a, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x50, 0x6f, 0x64, 0x73, 0x12, 0x1d, 0x2e, 0x70, 0x72,
	0x6f, 0x64, 0x76, 0x61, 0x6e, 0x61, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x52, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x50, 0x6f, 0x64, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x1e, 0x2e, 0x70, 0x72, 0x6f,
	0x64, 0x76, 0x61, 0x6e, 0x61, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x52, 0x65, 0x63, 0x6f,
	0x72, 0x64, 0x50, 0x6f, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x5f, 0x0a, 0x10,
	0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74,
	0x12, 0x23, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x76, 0x61, 0x6e, 0x61, 0x2e, 0x61, 0x67, 0x65, 0x6e,
	0x74, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65,
	0x6e, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x24, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x76, 0x61, 0x6e, 0x61,
	0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x44, 0x65, 0x70,
	0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x56, 0x0a,
	0x0d, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x6f, 0x6c, 0x6c, 0x6f, 0x75, 0x74, 0x12, 0x20,
	0x2e, 0x70, 0x72, 0x6f, 0x64, 0x76, 0x61, 0x6e, 0x61, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e,
	0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x6f, 0x6c, 0x6c, 0x6f, 0x75, 0x74, 0x52, 0x65, 0x71,
	0x1a, 0x21, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x76, 0x61, 0x6e, 0x61, 0x2e, 0x61, 0x67, 0x65, 0x6e,
	0x74, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x6f, 0x6c, 0x6c, 0x6f, 0x75, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x5d, 0x0a, 0x0e, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x41, 0x50,
	0x49, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x21, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x76, 0x61,
	0x6e, 0x61, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x41, 0x50,
	0x49, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x22, 0x2e, 0x70, 0x72, 0x6f,
	0x64, 0x76, 0x61, 0x6e, 0x61, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x50, 0x72, 0x6f, 0x78,
	0x79, 0x41, 0x50, 0x49, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00,
	0x28, 0x01, 0x30, 0x01, 0x12, 0x5c, 0x0a, 0x0f, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x44, 0x65,
	0x62, 0x75, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x22, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x76, 0x61,
	0x6e, 0x61, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x44,
	0x65, 0x62, 0x75, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x1a, 0x23, 0x2e, 0x70, 0x72,
	0x6f, 0x64, 0x76, 0x61, 0x6e, 0x61, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x52, 0x65, 0x70,
	0x6f, 0x72, 0x74, 0x44, 0x65, 0x62, 0x75, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70,
	0x22, 0x00, 0x1a, 0x10, 0xfa, 0xd2, 0xe4, 0x93, 0x02, 0x0a, 0x12, 0x08, 0x49, 0x4e, 0x54, 0x45,
	0x52, 0x4e, 0x41, 0x4c, 0x42, 0x4a, 0x5a, 0x48, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x70, 0x72, 0x6f, 0x64, 0x76, 0x61, 0x6e, 0x61, 0x2f, 0x70, 0x72, 0x6f, 0x64,
	0x76, 0x61, 0x6e, 0x61, 0x2d, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2f, 0x67, 0x6f, 0x2f, 0x70,
	0x72, 0x6f, 0x64, 0x76, 0x61, 0x6e, 0x61, 0x2d, 0x73, 0x64, 0x6b, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x64, 0x76, 0x61, 0x6e, 0x61, 0x2f, 0x61, 0x67, 0x65, 0x6e, 0x74,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_prodvana_agent_agent_interaction_proto_rawDescOnce sync.Once
	file_prodvana_agent_agent_interaction_proto_rawDescData = file_prodvana_agent_agent_interaction_proto_rawDesc
)

func file_prodvana_agent_agent_interaction_proto_rawDescGZIP() []byte {
	file_prodvana_agent_agent_interaction_proto_rawDescOnce.Do(func() {
		file_prodvana_agent_agent_interaction_proto_rawDescData = protoimpl.X.CompressGZIP(file_prodvana_agent_agent_interaction_proto_rawDescData)
	})
	return file_prodvana_agent_agent_interaction_proto_rawDescData
}

var file_prodvana_agent_agent_interaction_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_prodvana_agent_agent_interaction_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_prodvana_agent_agent_interaction_proto_goTypes = []interface{}{
	(InformerAction)(0),              // 0: prodvana.agent.InformerAction
	(RecordPushCompleteReq_Type)(0),  // 1: prodvana.agent.RecordPushCompleteReq.Type
	(ProxyAPIServerResp_Type)(0),     // 2: prodvana.agent.ProxyAPIServerResp.Type
	(*HeartbeatReq)(nil),             // 3: prodvana.agent.HeartbeatReq
	(*HeartbeatResp)(nil),            // 4: prodvana.agent.HeartbeatResp
	(*RecordNewUnknownPushReq)(nil),  // 5: prodvana.agent.RecordNewUnknownPushReq
	(*RecordNewUnknownPushResp)(nil), // 6: prodvana.agent.RecordNewUnknownPushResp
	(*RecordPushStartReq)(nil),       // 7: prodvana.agent.RecordPushStartReq
	(*RecordPushStartResp)(nil),      // 8: prodvana.agent.RecordPushStartResp
	(*RecordPushOngoingReq)(nil),     // 9: prodvana.agent.RecordPushOngoingReq
	(*RecordPushOngoingResp)(nil),    // 10: prodvana.agent.RecordPushOngoingResp
	(*RecordPushCompleteReq)(nil),    // 11: prodvana.agent.RecordPushCompleteReq
	(*RecordPushCompleteResp)(nil),   // 12: prodvana.agent.RecordPushCompleteResp
	(*ConfirmPushApprovalReq)(nil),   // 13: prodvana.agent.ConfirmPushApprovalReq
	(*ConfirmPushApprovalResp)(nil),  // 14: prodvana.agent.ConfirmPushApprovalResp
	(*RecordPodReq)(nil),             // 15: prodvana.agent.RecordPodReq
	(*RecordPodResp)(nil),            // 16: prodvana.agent.RecordPodResp
	(*RecordPodsReq)(nil),            // 17: prodvana.agent.RecordPodsReq
	(*RecordPodsResp)(nil),           // 18: prodvana.agent.RecordPodsResp
	(*RecordDeploymentReq)(nil),      // 19: prodvana.agent.RecordDeploymentReq
	(*RecordDeploymentResp)(nil),     // 20: prodvana.agent.RecordDeploymentResp
	(*RecordRolloutReq)(nil),         // 21: prodvana.agent.RecordRolloutReq
	(*RecordRolloutResp)(nil),        // 22: prodvana.agent.RecordRolloutResp
	(*ProxyAPIServerReq)(nil),        // 23: prodvana.agent.ProxyAPIServerReq
	(*ProxyAPIServerResp)(nil),       // 24: prodvana.agent.ProxyAPIServerResp
	(*DebugInfo)(nil),                // 25: prodvana.agent.DebugInfo
	(*ReportDebugInfoReq)(nil),       // 26: prodvana.agent.ReportDebugInfoReq
	(*ReportDebugInfoResp)(nil),      // 27: prodvana.agent.ReportDebugInfoResp
	(*timestamppb.Timestamp)(nil),    // 28: google.protobuf.Timestamp
}
var file_prodvana_agent_agent_interaction_proto_depIdxs = []int32{
	28, // 0: prodvana.agent.RecordNewUnknownPushReq.creation_timestamp:type_name -> google.protobuf.Timestamp
	28, // 1: prodvana.agent.RecordPushStartReq.creation_timestamp:type_name -> google.protobuf.Timestamp
	28, // 2: prodvana.agent.RecordPushStartReq.start_timestamp:type_name -> google.protobuf.Timestamp
	28, // 3: prodvana.agent.RecordPushOngoingReq.creation_timestamp:type_name -> google.protobuf.Timestamp
	28, // 4: prodvana.agent.RecordPushCompleteReq.creation_timestamp:type_name -> google.protobuf.Timestamp
	1,  // 5: prodvana.agent.RecordPushCompleteReq.type:type_name -> prodvana.agent.RecordPushCompleteReq.Type
	28, // 6: prodvana.agent.ConfirmPushApprovalReq.creation_timestamp:type_name -> google.protobuf.Timestamp
	0,  // 7: prodvana.agent.RecordPodReq.action:type_name -> prodvana.agent.InformerAction
	0,  // 8: prodvana.agent.RecordDeploymentReq.action:type_name -> prodvana.agent.InformerAction
	28, // 9: prodvana.agent.RecordDeploymentResp.push_timestamp:type_name -> google.protobuf.Timestamp
	0,  // 10: prodvana.agent.RecordRolloutReq.action:type_name -> prodvana.agent.InformerAction
	28, // 11: prodvana.agent.RecordRolloutResp.push_timestamp:type_name -> google.protobuf.Timestamp
	2,  // 12: prodvana.agent.ProxyAPIServerResp.type:type_name -> prodvana.agent.ProxyAPIServerResp.Type
	25, // 13: prodvana.agent.ReportDebugInfoReq.info:type_name -> prodvana.agent.DebugInfo
	3,  // 14: prodvana.agent.AgentInteraction.Heartbeat:input_type -> prodvana.agent.HeartbeatReq
	13, // 15: prodvana.agent.AgentInteraction.ConfirmPushApproval:input_type -> prodvana.agent.ConfirmPushApprovalReq
	5,  // 16: prodvana.agent.AgentInteraction.RecordNewUnknownPush:input_type -> prodvana.agent.RecordNewUnknownPushReq
	7,  // 17: prodvana.agent.AgentInteraction.RecordPushStart:input_type -> prodvana.agent.RecordPushStartReq
	9,  // 18: prodvana.agent.AgentInteraction.RecordPushOngoing:input_type -> prodvana.agent.RecordPushOngoingReq
	11, // 19: prodvana.agent.AgentInteraction.RecordPushComplete:input_type -> prodvana.agent.RecordPushCompleteReq
	15, // 20: prodvana.agent.AgentInteraction.RecordPod:input_type -> prodvana.agent.RecordPodReq
	17, // 21: prodvana.agent.AgentInteraction.RecordPods:input_type -> prodvana.agent.RecordPodsReq
	19, // 22: prodvana.agent.AgentInteraction.RecordDeployment:input_type -> prodvana.agent.RecordDeploymentReq
	21, // 23: prodvana.agent.AgentInteraction.RecordRollout:input_type -> prodvana.agent.RecordRolloutReq
	23, // 24: prodvana.agent.AgentInteraction.ProxyAPIServer:input_type -> prodvana.agent.ProxyAPIServerReq
	26, // 25: prodvana.agent.AgentInteraction.ReportDebugInfo:input_type -> prodvana.agent.ReportDebugInfoReq
	4,  // 26: prodvana.agent.AgentInteraction.Heartbeat:output_type -> prodvana.agent.HeartbeatResp
	14, // 27: prodvana.agent.AgentInteraction.ConfirmPushApproval:output_type -> prodvana.agent.ConfirmPushApprovalResp
	6,  // 28: prodvana.agent.AgentInteraction.RecordNewUnknownPush:output_type -> prodvana.agent.RecordNewUnknownPushResp
	8,  // 29: prodvana.agent.AgentInteraction.RecordPushStart:output_type -> prodvana.agent.RecordPushStartResp
	10, // 30: prodvana.agent.AgentInteraction.RecordPushOngoing:output_type -> prodvana.agent.RecordPushOngoingResp
	12, // 31: prodvana.agent.AgentInteraction.RecordPushComplete:output_type -> prodvana.agent.RecordPushCompleteResp
	16, // 32: prodvana.agent.AgentInteraction.RecordPod:output_type -> prodvana.agent.RecordPodResp
	18, // 33: prodvana.agent.AgentInteraction.RecordPods:output_type -> prodvana.agent.RecordPodsResp
	20, // 34: prodvana.agent.AgentInteraction.RecordDeployment:output_type -> prodvana.agent.RecordDeploymentResp
	22, // 35: prodvana.agent.AgentInteraction.RecordRollout:output_type -> prodvana.agent.RecordRolloutResp
	24, // 36: prodvana.agent.AgentInteraction.ProxyAPIServer:output_type -> prodvana.agent.ProxyAPIServerResp
	27, // 37: prodvana.agent.AgentInteraction.ReportDebugInfo:output_type -> prodvana.agent.ReportDebugInfoResp
	26, // [26:38] is the sub-list for method output_type
	14, // [14:26] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_prodvana_agent_agent_interaction_proto_init() }
func file_prodvana_agent_agent_interaction_proto_init() {
	if File_prodvana_agent_agent_interaction_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_prodvana_agent_agent_interaction_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeartbeatReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_prodvana_agent_agent_interaction_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeartbeatResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_prodvana_agent_agent_interaction_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecordNewUnknownPushReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_prodvana_agent_agent_interaction_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecordNewUnknownPushResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_prodvana_agent_agent_interaction_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecordPushStartReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_prodvana_agent_agent_interaction_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecordPushStartResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_prodvana_agent_agent_interaction_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecordPushOngoingReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_prodvana_agent_agent_interaction_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecordPushOngoingResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_prodvana_agent_agent_interaction_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecordPushCompleteReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_prodvana_agent_agent_interaction_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecordPushCompleteResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_prodvana_agent_agent_interaction_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfirmPushApprovalReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_prodvana_agent_agent_interaction_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfirmPushApprovalResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_prodvana_agent_agent_interaction_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecordPodReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_prodvana_agent_agent_interaction_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecordPodResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_prodvana_agent_agent_interaction_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecordPodsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_prodvana_agent_agent_interaction_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecordPodsResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_prodvana_agent_agent_interaction_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecordDeploymentReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_prodvana_agent_agent_interaction_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecordDeploymentResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_prodvana_agent_agent_interaction_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecordRolloutReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_prodvana_agent_agent_interaction_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecordRolloutResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_prodvana_agent_agent_interaction_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProxyAPIServerReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_prodvana_agent_agent_interaction_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProxyAPIServerResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_prodvana_agent_agent_interaction_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DebugInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_prodvana_agent_agent_interaction_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReportDebugInfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_prodvana_agent_agent_interaction_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReportDebugInfoResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_prodvana_agent_agent_interaction_proto_msgTypes[20].OneofWrappers = []interface{}{
		(*ProxyAPIServerReq_RuntimeId)(nil),
		(*ProxyAPIServerReq_Blob)(nil),
	}
	file_prodvana_agent_agent_interaction_proto_msgTypes[21].OneofWrappers = []interface{}{
		(*ProxyAPIServerResp_Type_)(nil),
		(*ProxyAPIServerResp_Blob)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_prodvana_agent_agent_interaction_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_prodvana_agent_agent_interaction_proto_goTypes,
		DependencyIndexes: file_prodvana_agent_agent_interaction_proto_depIdxs,
		EnumInfos:         file_prodvana_agent_agent_interaction_proto_enumTypes,
		MessageInfos:      file_prodvana_agent_agent_interaction_proto_msgTypes,
	}.Build()
	File_prodvana_agent_agent_interaction_proto = out.File
	file_prodvana_agent_agent_interaction_proto_rawDesc = nil
	file_prodvana_agent_agent_interaction_proto_goTypes = nil
	file_prodvana_agent_agent_interaction_proto_depIdxs = nil
}
